# tasks/main.yml
---
- name: Validate that all users have a valid name
  ansible.builtin.assert:
    that:
      - "(item.name | default(item)) | string | length > 0"
      - "(item.name | default(item)) is match('^[a-z][a-z0-9_-]*$')"
    fail_msg: >
      Each user must start with a lowercase letter, followed by
      lowercase letters, digits, underscores, or dashes.
  loop: "{{ users_add }}"
  loop_control:
    label: "{{ item.name | default(item) }}"
  tags:
    - users
    - users_add
    - validate


- name: Add users
  ansible.builtin.user:
    name: "{{ item.name | default(item) }}"
    comment: "{{ item.comment | default('') }}"
    createhome: true
    groups: "{{ item.groups | default([]) | join(',') }}"
    home: "{{ item.home | default('/home/' ~ (item.name | default(item))) }}"
    shell: "{{ item.shell | default('/bin/bash') }}"
    state: present
  loop: "{{ users_add }}"
  tags:
    - users
    - users_add

- name: Ensure ~/.ssh directory exists for users with ssh_keys
  ansible.builtin.file:
    path: "{{ item.home | default('/home/' + item.name) }}/.ssh"
    state: directory
    owner: "{{ item.name }}"
    group: "{{ item.name }}"
    mode: "0700"
  loop: "{{ users_add }}"
  when: item.ssh_keys is defined
  tags:
    - users
    - users_add
    - ssh_keys

- name: Create authorized_keys file from template
  ansible.builtin.template:
    src: authorized_keys.j2
    dest: "{{ item.home | default('/home/' + item.name) }}/.ssh/authorized_keys"
    owner: "{{ item.name }}"
    group: "{{ item.name }}"
    mode: "0600"
  loop: "{{ users_add }}"
  when: item.ssh_keys is defined
  vars:
    ssh_keys: "{{ item.ssh_keys }}"
  tags:
    - users
    - users_add
    - ssh_keys

- name: Delete users
  ansible.builtin.user:
    name: "{{ item.name | default(item) }}"
    state: absent
  loop: "{{ users_del }}"
  tags:
    - users
    - users_del
