# molecule/default/converge.yml
---
- name: Converge
  hosts: all

  pre_tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 600
      register: apt_cache_update
      when: ansible_os_family == 'Debian'

    - name: Set users_to_add
      ansible.builtin.set_fact:
        users_add:
          - name: deploy
            comment: "Deploy user"
            ssh_keys:
              - "ssh-ed25519 AAAAC3NzaC1 user1@email.com"
              - "ssh-ed25519 AAAAC3NzaC2 user2@email.com"
              - "ssh-ed25519 AAAAC3NzaC3 user3@email.com"

          - name: devops
            groups:
              - sudo
            ssh_keys:
              - "ssh-ed25519 AAAAC3NzaC1 user1@email.com"

          - foo

  roles:
    - { role: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}" }
